### PR TITLE
DOC: Add Python package installation instructions

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
> I haven't tried this style python for a while, but the ability to add modules looks great.

This also benefits automatic improvements the improvements in the wrapping infrastructure, e.g. the generated functional Python interface:

```
import itk

image = itk.imread('image.mha')
dilated = itk.parabolic_dilate_image_filter(image)
```

> I would like to highlight the need to have the appropriate tag included in ITK so that the right version is pulled when the module build is requested.

Good point. To enforce this and release a new package with the update, first a pull request is created to update:

https://github.com/InsightSoftwareConsortium/ITKParabolicMorphology/blob/f8a1e7bba9b0c187a7480339f2df3b0304913c04/setup.py#L52

to

`r'itk>=5.1.0'`

and update the `version`:

https://github.com/InsightSoftwareConsortium/ITKParabolicMorphology/blob/f8a1e7bba9b0c187a7480339f2df3b0304913c04/setup.py#L16

to 

`1.0.1`

Then create a `v1.0.1` tag on the Releases tab:

https://github.com/InsightSoftwareConsortium/ITKParabolicMorphology/releases


@richardbeare would you like to give it a try?

**Comment by richardbeare** [comment]
What is the procedure for the ITK side? i.e. so that building the module is ITK retrieves the right version. Is it possible to have this happed in the current ITK release/

**Comment by thewtex** [comment]
In ITK, the commit hash can be updated here:

https://github.com/InsightSoftwareConsortium/ITK/blob/27258efa6ba74228958af7b5a620d005c644da51/Modules/Remote/ParabolicMorphology.remote.cmake#L52

**Comment by richardbeare** [comment]
@thewtex Regarding tagging. The latest tag is v3.0. How do you want to align the python module versions?

**Pull request merged**
